# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-01 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170501_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
